name: Typos

on:
  pull_request:
    paths:
      - "src/**"
      - "public/**"
      - "docs/**"
      - ".github/workflows/typos.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "docs/**"
      - ".github/workflows/typos.yml"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: crate-ci/typos@bbaefadf97b0ec5fdc942684b647f1a6ab250274 # v1.46.0
