name: Typos

on:
  pull_request:
    paths:
      - "src/**"
      - "public/**"
      - "docs/**"
      - ".github/workflows/typos.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "docs/**"
      - ".github/workflows/typos.yml"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
